module WasmEdge.Configure
  ( ConfigureContext
  , configureCreate
  , configureAddProposal
  , configureRemoveProposal
  , configureHasProposal
  , configureAddHostRegistration
  , configureRemoveHostRegistration
  , configureHasHostRegistration
  , configureSetMaxMemoryPage
  , configureSetForceInterpreter
  , configureIsForceInterpreter
  , configureCompilerSetOptimizationLevel
  , configureCompilerGetOptimizationLevel
  , configureCompilerSetOutputFormat
  , configureCompilerGetOutputFormat
  , configureCompilerSetDumpIR
  , configureCompilerIsDumpIR
  , configureCompilerSetGenericBinary
  , configureCompilerIsGenericBinary
  , configureCompilerSetInterruptible
  , configureCompilerIsInterruptible
  , configureStatisticsSetInstructionCounting
  , configureStatisticsIsInstructionCounting
  , configureStatisticsSetCostMeasuring
  , configureStatisticsIsCostMeasuring
  , configureStatisticsSetTimeMeasuring
  , configureStatisticsIsTimeMeasuring
  ) where

import WasmEdge.Internal.FFI.Bindings
    ( ConfigureContext
  , configureCreate
  , configureAddProposal
  , configureRemoveProposal
  , configureHasProposal
  , configureAddHostRegistration
  , configureRemoveHostRegistration
  , configureHasHostRegistration
  , configureSetMaxMemoryPage
  , configureSetForceInterpreter
  , configureIsForceInterpreter
  , configureCompilerSetOptimizationLevel
  , configureCompilerGetOptimizationLevel
  , configureCompilerSetOutputFormat
  , configureCompilerGetOutputFormat
  , configureCompilerSetDumpIR
  , configureCompilerIsDumpIR
  , configureCompilerSetGenericBinary
  , configureCompilerIsGenericBinary
  , configureCompilerSetInterruptible
  , configureCompilerIsInterruptible
  , configureStatisticsSetInstructionCounting
  , configureStatisticsIsInstructionCounting
  , configureStatisticsSetCostMeasuring
  , configureStatisticsIsCostMeasuring
  , configureStatisticsSetTimeMeasuring
  , configureStatisticsIsTimeMeasuring )
