name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.2.8'
        cabal-version: '3.6'
    
    - name: cache
      id: cache-wasmedge
      uses: actions/cache@v3
      with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
            ~/.wasmedge
          key: |
            ${{ runner.os }}-${{ matrix.ghc }}-v1-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project*') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-v1-
    
    - name: Install dependencies
      run: |
        cabal build all --only-dependencies
        
    - name: Install WasmEdge C library
      if: steps.cache-wasmedge.outputs.cache-hit != 'true'
      run: | 
        VERSION=0.13.3
        curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v $VERSION
    
    - name: Build
      run: |
        source $HOME/.wasmedge/env
        cabal build --flags="TestOnly"
        
    - name: Test
      run: |
        source $HOME/.wasmedge/env
        cabal test all --flags="TestOnly"
